version : '3'
 
services:
  peopleapi:
    image: people-api-pipeline
    ports:
      - 9004:8080
    environment:
      - peopleapicontext=server=people-api-db-pipeline;user id=peopleAPI;password=myP@ssw0rd;Database=peopleAPI
    depends_on:
      - people-api-db-pipeline
  
  people-api-db-pipeline:
    image: people-api-db-pipeline
    ports:
      - 1433
